# Site settings
title: Tammy Does The Needful
header-img: img/home-bg.png
email: tammy@tammymetz.com
copyright_name: tmetz
description: > # this means to ignore newlines until "baseurl:"
  Adventures in Learning Ruby, JavaScript, and All The Things
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tmetz
learn_profile: tmetz
email_username: tammy@tammymetz.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
